### ISSUE TITLE
FileNotFoundError: [WinError 2]

### ISSUE THREAD

**Issue by fazhang-master** [LBC-LNBio/parKVFinder-win#2] opened 2023-11-19 14:39 UTC
[==> Running parKVFinder for: I:\pymol\KV_Files\output\1FMO.pdb
Traceback (most recent call last):
  File "I:\pymol\lib\site-packages\pmg_tk\startup\PyMOL2-parKVFinder-Tools\__init__.py", line 283, in run
    subprocess.call(self.parKVFinder.text().replace(' ', '\\ '), stdout=subprocess.PIPE)
  File "I:\pymol\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "I:\pymol\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "I:\pymol\lib\subprocess.py", line 1436, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by jvsguerra** [comment] 2023-11-21 13:57
Hi @fage66639,

Considering the error message you've shared, I've identified a couple of potential causes for the issue:

1. It is possible that the installation of parKVFinder-win64.exe has not been completed correctly. Please double-check if you have properly set KVFinder_PATH with the absolute path to the parKVFinder-win directory. For detailed installation instructions, you can refer to [this link](https://github.com/LBC-LNBio/parKVFinder-win#download--installation).

2. Another potential issue could be related to permissions. Verify whether PyMOL or parKVFinder has the necessary permissions to access the specified file.

Additionally, we have released a web version of parKVFinder called KVFinder-web. You can access it at https://kvfinder-web.cnpem.br/. For more details, refer to the corresponding article: https://academic.oup.com/nar/article/51/W1/W289/7151338.

Feel free to check these suggestions, and if the issue persists, provide additional details for further assistance.

**Comment by YeeZh-i** [comment] 2023-11-23 09:29
You miss the file "parKVFinder-win64.exe." To resolve this, you need to download the compressed file from the "code" interface (the compressed file will be named "parKVFinder-win-master"). After extracting it, set it as an environment variable with the name "KVFinder_PATH," and then restart the system to run it.

**Comment by jvsguerra** [comment] 2023-12-19 15:49
@fage66639, I am closing this issue for now.
If you feel that the issue is still relevant or have any further questions, please feel free to re-open it and provide any additional information that may be helpful in resolving the issue.

**Closed as completed by jvsguerra** 2023-12-19 15:49 UTC
Labels: help wanted, question
