### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Programs\\PyMOL\\KV_Files\\output\\output.KVFinder.results.toml'

### ISSUE THREAD

**Issue by NONOBread** [LBC-LNBio/parKVFinder-win#3] opened 2024-01-27 14:11 UTC
[==> Running parKVFinder for: D:\Programs\PyMOL\KV_Files\output\1FMO.pdb
Traceback (most recent call last):
  File "D:\Programs\PyMOL\lib\site-packages\pmg_tk\startup\PyMOL2-parKVFinder-Tools-backup\__init__.py", line 285, in run
    ncavs = self.get_number_of_cavities()
  File "D:\Programs\PyMOL\lib\site-packages\pmg_tk\startup\PyMOL2-parKVFinder-Tools-backup\__init__.py", line 317, in get_number_of_cavities
    with open(f"{os.path.join(self.output_dir_path.text(), 'KV_Files', self.base_name.text(), f'{self.base_name.text()}.KVFinder.results.toml')}") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Programs\\PyMOL\\KV_Files\\output\\output.KVFinder.results.toml'

**Comment by jvsguerra** [comment] 2024-01-27 22:15
Hi @NONOBread,

Considering the error message you have shared, it appears that parKVFinder is executing successfully on your system but encountering issues with read/write operations in the directory `D:\Programs\PyMOL\`.

First, change the `Output directory:` in the PyMOL plugin (e.g., `D:\Documents`, `D:\Downloads`) and run parKVFinder again. Please check if the output directory is being created.  Confirm that parKVFinder files (e.g., `KVFinder.log`, `output.KVFinder.results.toml`, and `output.KVFinder.output.pdb`) are generated in this directory.

If the problem persists, could you provide details about your installation process?

As an alternative, we have released a web version of parKVFinder (v1.2.0) called KVFinder-web, featuring depth and hydropathy characterization. You can access it at https://kvfinder-web.cnpem.br/. For more details, refer to the corresponding article: https://academic.oup.com/nar/article/51/W1/W289/7151338.

**Comment by jvsguerra** [comment] 2024-03-07 17:30
Hi @NONOBread,

I just wanted to let you know that I am closing this issue for now.
If you feel that the issue is still relevant or have any further questions, please re-open it and provide any additional information that may help resolve it.

**Closed as completed by jvsguerra** 2024-03-07 17:30 UTC
Labels: help wanted
